version: "3.8"

services:
  twilio-server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - BACK_URL=${BACK_URL}
      - AUTH_TOKEN=${AUTH_TOKEN}
    restart: always
